### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [RHVoice/Polish#1]
Hello!

Could you please add the license information to the repository?
Is it the same as https://github.com/RHVoice/RHVoice , GPL v2?

**Comment by zstanecic** [comment]
Hi @vazhnov
, The language binaries in this repository, as well as the sourcee code are licensed under gpl V 2.1

**Comment by vazhnov** [comment]
Could you please add a `LICENSE.txt` or something like it?

**Comment by zstanecic** [comment]
Yes, i can add this metadata.

**Comment by zstanecic** [comment]
@vazhnov 
done
